<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/gyrationtechs/image/upload/c_scale,h_200,w_200/v1554438457/David.png" alt="David Ozokoye">
                        <h6>David Ozokoye</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="https://www.twitter.com/gyrationtech" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/gyrationtechs" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="https://medium.com/@davidozokoye" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>Hello, I'm David Ozokoye, a final year student of Electrical/Electronics Engineering. I am a front-end developer aspiring to be a full-stack python developer.</p>
                        <br />
                        <h6>Skills</h6>
                        <p>HTML | Boostrap | Python</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
